#!/usr/bin/env node
// Switches the active Firebase project: copies .env.<name> to .env, then
// regenerates web/firebase-config.js and .firebaserc from it (both are
// gitignored, derived files — see the matching *.example files).
// Usage: node scripts/use-project.js <name>   (e.g. terapeuta, mio)
const fs = require('fs');
const path = require('path');

const name = process.argv[2];
if (!name) {
  console.error('Usage: node scripts/use-project.js <name>   (e.g. terapeuta, mio)');
  process.exit(1);
}

const root = path.resolve(__dirname, '..');
const sourceEnvPath = path.join(root, `.env.${name}`);

if (!fs.existsSync(sourceEnvPath)) {
  console.error(`Missing ${sourceEnvPath}. Copy .env.example to .env.${name} and fill in real values first.`);
  process.exit(1);
}

const envContents = fs.readFileSync(sourceEnvPath, 'utf8');
fs.writeFileSync(path.join(root, '.env'), envContents);

const vars = {};
for (const line of envContents.split('\n')) {
  const match = line.match(/^([A-Z0-9_]+)=(.*)$/);
  if (match) vars[match[1]] = match[2].trim();
}

const required = [
  'EXPO_PUBLIC_FIREBASE_API_KEY',
  'EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN',
  'EXPO_PUBLIC_FIREBASE_PROJECT_ID',
  'EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET',
  'EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID',
  'EXPO_PUBLIC_FIREBASE_APP_ID',
];
const missing = required.filter((key) => !vars[key]);
if (missing.length) {
  console.error(`${sourceEnvPath} is missing: ${missing.join(', ')}`);
  process.exit(1);
}

const webConfig = `// Generated by "node scripts/use-project.js ${name}" from .env.${name} —
// do not edit directly, it will be overwritten on the next switch.
export const firebaseConfig = {
  apiKey: '${vars.EXPO_PUBLIC_FIREBASE_API_KEY}',
  authDomain: '${vars.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN}',
  projectId: '${vars.EXPO_PUBLIC_FIREBASE_PROJECT_ID}',
  storageBucket: '${vars.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET}',
  messagingSenderId: '${vars.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}',
  appId: '${vars.EXPO_PUBLIC_FIREBASE_APP_ID}',
};
`;
fs.writeFileSync(path.join(root, 'web', 'firebase-config.js'), webConfig);

// Preserve any existing "targets"/"etags" (hosting multi-site config isn't
// tied to which project is currently active) — only swap projects.default.
const firebasercPath = path.join(root, '.firebaserc');
let firebaserc = {};
if (fs.existsSync(firebasercPath)) {
  try {
    firebaserc = JSON.parse(fs.readFileSync(firebasercPath, 'utf8'));
  } catch {
    firebaserc = {};
  }
}
firebaserc.projects = { ...firebaserc.projects, default: vars.EXPO_PUBLIC_FIREBASE_PROJECT_ID };
fs.writeFileSync(firebasercPath, JSON.stringify(firebaserc, null, 2) + '\n');

console.log(`Switched to "${name}" (${vars.EXPO_PUBLIC_FIREBASE_PROJECT_ID}).`);
console.log('Updated: .env, web/firebase-config.js, .firebaserc');
